server:
  port: 8083
  servlet:
    # Tutte le chiamate saranno hostname:port/post
    context-path: /object

spring:
  config:
    activate:
      on-profile: object
  application:
    name: msobject


app:
  name: object
  items: craft, booktoe, ringcheck, bookbangle, braceletpacket of seedsstreet, lightsmatchbookrubber, duckextension, cordbananapailmartini, glasssquirreldogcorkroll of masking, tapepantscontainer of puddingwristwatchscrewdriverlionhelmetkey, chainboxquartz, crystalfew, batteriesspoonpair of glassesnotepadtennis, racket
