server:
  port: 8081
  servlet:
    # Tutte le chiamate saranno hostname:port/post
    context-path: /subject

spring:
  config:
    activate:
      on-profile: subject
  application:
    name: mssubject

app:
  name: subject
  items: car, dog, soccer, music, painting, mathematics, biology, geography, language, poetry, cooking, hiking, wildlife, cinema, ballet, photography, technology, fashion, wellness, yoga
