server:
  port: 8083
  servlet:
    # Tutte le chiamate saranno hostname:port/post
    context-path: /object

spring:
  config:
    activate:
      on-profile: object
  application:
    name: msobject


app:
  name: object
  items: dog, cat, sport, music, art, math, science, history, language, literature, food, travel, nature, film, dance, photography, technology, fashion, health, fitness
