server:
  port: 8082
  servlet:
    # Tutte le chiamate saranno hostname:port/verb
    context-path: /verb

spring:
  config:
    activate:
      on-profile: verb
  application:
    name: msverb


app:
  name: verb
  items: runs, sings, dances, paints, cooks, writes, reads, codes, swims, explores, travels, hikes, photographs, designs, styles, creates, inspires, motivates, meditates, communicates
